### ISSUE TITLE
Squirls database files unavailable (403 Forbidden)

### ISSUE THREAD

**Issue by oyvinev** [TheJacksonLaboratory/Squirls#31]
Attempting to download https://squirls.s3.amazonaws.com/2102_hg19.zip gives a 403 Forbidden error:

![image](https://user-images.githubusercontent.com/4920368/116671150-e4989b00-a9a0-11eb-8d9c-716af1bb7832.png)

**Comment by ielis** [comment]
Hi @oyvinev, there is a new version of the database available at
- https://squirls.s3.amazonaws.com/2103_hg19.zip
- https://squirls.s3.amazonaws.com/2103_hg38.zip


I forgot to update the documentation, sorry for that.

**Comment by oyvinev** [comment]
Thanks for the quick reply!
