### ISSUE TITLE
Extracting the SQUIRL features without prediction

### ISSUE THREAD

**Issue by dagap** [TheJacksonLaboratory/Squirls#35]
Is there an appl already within the framework to just extract the SQUIRL features for an input dataset? If not, could you advise on which app to look at and possibly modify to just extract that functionality?

My interest is to extract the SQUIRL features and serialize them and then potentially input them to other ML models.

**Comment by ielis** [comment]
Hi @dagap , there are two ways how to get ahold of SQUIRLS features.

First is to use `--report-features` CLI flag as described at the end of the [CSV/TSV output format](https://squirls.readthedocs.io/en/latest/outputformats.html#csv-tsv-output-format). Using `--report-features` adds `squirls_features` column to the result table. You may need to do some postprocessing/text crunching to get the feature values.

As the second option, you can use SQUIRLS as a library if you're comfortable with writing Java code. First you need to do a local install (`./mvnw install`), include `squirls-bootstrap` as a dependency, and use it to create `Squirls` object. All this is described in [Use Squirls as a library](https://squirls.readthedocs.io/en/latest/library.html) section of the docs.

Then, something like the following should do the trick:
```java
Squirls squirls = ... ; // get the real object as described in the manual
VariantSplicingEvaluator evaluator = squirls.variantSplicingEvaluator();

Variant variant = ... ; // prepare a real variant as described in the manual 
SquirlsResult result = evaluator.evaluate(variant);
Map<String, Map<String, Double>> featuresByTxId = result.results()
    .collect(Collectors.toMap(SquirlsTxResult::accessionId, SquirlsTxResult::features));        
```
By running the code above you get `featuresByTxId` map - SQUIRLS features by the feature name (inner map key) by transcript accession ID (outer map key).

**Comment by dagap** [comment]
Thank you for such a detailed and quick reply! @ielis
