### ISSUE TITLE
Enhancement request - BCF support

### ISSUE THREAD

**Issue by kvn95ss** [TheJacksonLaboratory/Squirls#49]
Hello,

I was wondering if it would be possible to support bcf as input format. BCF files are pretty handy, especially when working with large amount of data.

**Comment by ielis** [comment]
Hi, sorry, but this seems like an issue a general bioinformatician should be able to solve with another tooling. It should be fairly straightforward to do something like:
```shell
cat example.bcf | bcdftools view -O z > example.vcf.gz
squirls annotate-vcf -d ... example.vcf.gz output
```

**Comment by kvn95ss** [comment]
Hay, yes it might sound trivial, but it involves writing a .vcf.gz to serve as input file and writing .vcf.gz output. If a tool supports BCF natively, the IO expense in first step will be spared. 

Regardless, just consider this a raving from BCF evangelist XD.
